src/classes/SalesCondition_ba.cls
=> 2025-04-14 SalesCondition_ba 수정_Final

.idea/inspectionProfiles/Project_Default.xml, src/classes/AsyncCustomsInfo.cls, src/classes/AsyncOrderConfirm.cls, src/classes/AsyncPurchaseInvoice.cls, src/classes/AsyncTaxInvoiceIssuance.cls, src/classes/CreateVehicleStock_ba.cls
1. AsyncTaxInvoiceIssuance
2. AsyncOrderConfirm
3. AsyncPurchaseInvoice
4. AsyncCustomsInfo
=> 1. BF 3종버튼 취소프로세스 추가 / 2. SMS013 세금계산서 변수변경

src/lwc/fileUploader/fileUploader.js
=> 2025 04-15 fileUploader

src/lwc/quoteCreator/quoteCreator.js
=> 2025-04-15

src/classes/PdiController.cls
=> 250416 pdi 컨트롤러

src/lwc/pdiStep0View/pdiStep0View.js
=> 250416 PDI step0 오류 수정 테스트

src/lwc/pdiStep0View/pdiStep0View.js
=> 250416 PDI step0

.forceignore, sfdx-project.json
=> 2025-04-16 accTest

src/lwc/quoteCreator/quoteCreator.css
=> 2025-04-16

src/classes/CreateAssignRequestController.cls, src/lwc/depositInvoice/depositInvoice.js
console.log, System.debug 제거 및 미사용 메서드 주석 제거
사업자번호와 주민등록번호 OR 조건으로 수정
=> 250421 계약금 요청 수정

src/pages/ModusignPDFTemplate.page
=> 2025-04-22 계약서 pdf 수정2

src/pages/ModusignPDFTemplate.page
=> 2025-04-22 계약서 pdf 수정 3

src/classes/ModuSignPDFController.cls
=> 2025-04-22 계약서 pdf 수정 5

src/classes/ModuSignPDFController.cls
=> 250422 계약서 수정

src/classes/ModuSignPDFController.cls, src/pages/ModusignPDFTemplate.page
=> 250422 계약서 pdf 수정2

src/classes/ModuSignPDFController.cls, src/pages/ModusignPDFTemplate.page
=> 2024-04-22 계약서 pdf, class 수정

src/classes/PdiController.cls, src/lwc/pdiMain/pdiMain.html, src/lwc/pdiMain/pdiMain.js, src/lwc/pdiStep1View/pdiStep1View.html, src/lwc/pdiStep1View/pdiStep1View.js, src/lwc/pdiStep2View/pdiStep2View.html, src/lwc/pdiStep2View/pdiStep2View.js, src/lwc/pdiStep5View/pdiStep5View.html, src/lwc/pdiStep5View/pdiStep5View.js
1. PDI Step1, 2, 5 주행거리 & 이슈 입력 후 단계 완료 버튼과 입력값 저장 버튼 분리
2. 1번 수정에 따른 PDIcontroller updateVehicleStock 로직 수정
3. PDI Step1, 2, 5 isAero > isSpoiler 필드 변경
=> 250422 PDI 주행거리&이슈 저장 수정

src/classes/LeadManagementController.cls, src/lwc/leadAcquisition/leadAcquisition.html, src/lwc/leadAcquisition/leadAcquisition.js
1. 리드 수집 화면에서 선수금을 입력해서 대출금을 계산해내도록 로직 수정
=> 250422 리드 수집 수정

src/classes/Contract_tr.cls
1. 금융회사가 MFS가 아닐 때 입금현황관리의 전체금액 계산 수정
=> 250423 Contract_tr 입금현황관리 생성 오류 수정

src/classes/PdiController.cls, src/lwc/pdiMain/pdiMain.html, src/lwc/pdiMain/pdiMain.js, src/lwc/pdiStep0View/pdiStep0View.css, src/lwc/pdiStep0View/pdiStep0View.html, src/lwc/pdiStep0View/pdiStep0View.js, src/lwc/pdiStep1View/pdiStep1View.css, src/lwc/pdiStep1View/pdiStep1View.html, src/lwc/pdiStep2View/pdiStep2View.css, src/lwc/pdiStep3View/pdiStep3View.html, src/lwc/pdiStep3View/pdiStep3View.js, src/lwc/pdiStep3View/pdiStep3ViewColumns.js, src/lwc/pdiStep4View/pdiStep4View.html, src/lwc/pdiStep4View/pdiStep4View.js, src/lwc/pdiStep5View/pdiStep5View.css
1. PDI 3단계 차량배정/취소 로직 추가 수정(선택 후 배정 완료시 다른 기회에 선택한 차량이 연결되어있으면 다른 기회에서 연결 해제)
2. PDI 3단계 선택한 차량이 배정된 기회가 없을 땐 출고예정서(핸드오버스케줄러에) 나오는 기회 전체 리스트업
3. PDI 메인 제목에 워크넘버 추가 및 글자 크기 조정
4. PDI lwc 전체 컬럼 크기 화면에 다 차도록 조정
=> 250423 PDI컨트롤러 수정

src/lwc/handoverScheduler/handoverScheduler.html
1. 핸드오버스케쥴러 '배정취소' 버튼 우선 숨김(관련된 기능은 천천히 제거하는 걸로...)
=> 250423 핸드오버스케쥴러 수정

src/classes/SchedulerMainController.cls, src/lwc/handoverScheduler/handoverSchedulerColumns.js
1. 핸드오버스케줄러의 워크넘버 컬럼을 클릭하면 PDI 메인으로 이동하도록 url로 변경
=> 240424 핸드오버스케줄러 수정

src/classes/ContractCancelController.cls, src/classes/ContractCancelController_test.cls, src/lwc/contractCancel/contractCancel.html, src/lwc/contractCancel/contractCancel.js, src/lwc/contractRenegotiation/contractRenegotiation.html, src/lwc/contractRenegotiation/contractRenegotiation.js, src/lwc/createContract/createContract.html, src/lwc/depositInvoice/depositInvoice.html, src/lwc/goodWillUsing/goodWillUsing.js, src/lwc/leadAcquisition/leadAcquisition.js, src/lwc/paymentTracker/paymentTracker.css, src/lwc/paymentTracker/paymentTracker.html, src/lwc/paymentTracker/paymentTracker.js, src/lwc/sendFilePublicLink/sendFilePublicLink.html
1. 계약 취소 버튼 클릭시 취소 사유 선택 화면 추가
2. 개발 LWC 팝업 버튼 순서 변경
3. 개발 LWC 토스트 title, content 변경
=> 250424 버튼 위치 변경 및 토스트 title, content 변경
